tcobro_WEB -Terminado - 01-08-2023 - 8.02h/tcobro_WEB/Controllers/EmpresaController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;
using tcobro_Utilidad;
using tcobro_WEB.Models;
using tcobro_WEB.Models.Dto;
using tcobro_WEB.Services.IServices;

namespace tcobro_WEB.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly IEmpresaService _empresaService;
        private readonly IMapper _mapper;

        public EmpresaController(IEmpresaService empresaService, IMapper mapper)
        {
            _empresaService = empresaService;
            _mapper = mapper;
        }


        /*Carga la lista de Empresas*/
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> IndexEmpresa()//Agregar vista con click derecho ->Vista Razor->(...)->View->Shared ->Layout
        {
            List<EmpresaDTO> empresaList = new(); //Trae una lista de todas las empresas

            var response = await _empresaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken)); //Obtiene todas las empresas y autentica con token

            if(response != null && response.IsExitoso)
            {
                empresaList = JsonConvert.DeserializeObject<List<EmpresaDTO>>(Convert.ToString(response.Resultado));
            }

            return View(empresaList);
        }

        /*Añadir Empresa*/

        //Metodo GET recibe los datos y llama a la vista (Agregar vista siempre con GET [linea 23])
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CrearEmpresa()
        {
            return View();
        }


        //Metodo POST que envia la informacion
        [HttpPost]
        [ValidateAntiForgeryToken]//Siempre que sea POST, implantar metodo de seguridad
        public async Task<IActionResult> CrearEmpresa(EmpresaCreateDTO empresa)
        {
            if(ModelState.IsValid)//Si estan todos los campos requeridos llenos
            {
                var response = await _empresaService.Crear<APIResponse>(empresa, HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

                if(response != null && response.IsExitoso)
                {
                    TempData["exitoso"] = "Empresa creada exitosamente"; //Datos en carpeta Shared
                    return RedirectToAction(nameof(IndexEmpresa)); //Redirecciona a la lista de Empresas
                }                
            }
            TempData["error"] = "Ha ocurrido un ERROR al crear empresa"; //Datos en carpeta Shared
            return View(empresa);
        }


        /*Actualizar Empresa*/

        //Metodo GET recibe los datos y llama a la vista (Agregar vista siempre con GET [linea 23])
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> ActualizarEmpresa(int empresaId)
        {
            var response = await _empresaService.Obtener<APIResponse>(empresaId, HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if(response != null && response.IsExitoso)
            {
                EmpresaDTO empresa = JsonConvert.DeserializeObject<EmpresaDTO>(Convert.ToString(response.Resultado));

                return View(_mapper.Map<EmpresaUpdateDTO>(empresa));
            }

            return NotFound(); //No se encontraron datos
        }

        //Metodo POST que envia la informacion
        [HttpPost]
        [ValidateAntiForgeryToken]//Siempre que sea POST, implantar metodo de seguridad
        public async Task<IActionResult> ActualizarEmpresa(EmpresaUpdateDTO empresa)
        {
            if(ModelState.IsValid)//Si estan todos los campos requeridos llenos
            {
                var response = await _empresaService.Actualizar<APIResponse>(empresa, HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

                if(response != null && response.IsExitoso)
                {
                    TempData["exitoso"] = "Empresa actualizada exitosamente"; //Datos en carpeta Shared
                    return RedirectToAction(nameof(IndexEmpresa));
                }
            }
            TempData["error"] = "Ha ocurrido un ERROR al actualizar empresa"; //Datos en carpeta Shared
            return View(empresa);
        }



        /*Borrar Empresa*/

        //Metodo GET recibe los datos y llama a la vista (Agregar vista siempre con GET [linea 23])
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> RemoverEmpresa(int empresaId)
        {
            var response = await _empresaService.Obtener<APIResponse>(empresaId, HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if (response != null && response.IsExitoso)
            {
                EmpresaDTO empresa = JsonConvert.DeserializeObject<EmpresaDTO>(Convert.ToString(response.Resultado));

                return View(empresa);
            }

            return NotFound(); //No se encontraron datos
        }

        //Metodo POST que envia la informacion
        [HttpPost]
        [ValidateAntiForgeryToken]//Siempre que sea POST, implantar metodo de seguridad
        public async Task<IActionResult> RemoverEmpresa(EmpresaDTO empresa)
        {
            
                var response = await _empresaService.Remover<APIResponse>(empresa.Id, HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

                if (response != null && response.IsExitoso)
                {
                TempData["exitoso"] = "Empresa eliminada exitosamente"; //Datos en carpeta Shared
                return RedirectToAction(nameof(IndexEmpresa));
                }
            TempData["error"] = "Ha ocurrido un ERROR al eliminar empresa"; //Datos en carpeta Shared
            return View(empresa);
        }

    }
}

tcobro_WEB -Terminado - 01-08-2023 - 8.02h/tcobro_WEB/Controllers/MaquinaController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Data;
using tcobro_Utilidad;
using tcobro_WEB.Models;
using tcobro_WEB.Models.Dto;
using tcobro_WEB.Models.ViewModel;
using tcobro_WEB.Services.IServices;

namespace tcobro_WEB.Controllers
{
    public class MaquinaController : Controller
    {
        private readonly IMaquinaService _maquinaService;
        private readonly IEmpresaService _empresaService;
        private readonly IMapper _mapper;

        public MaquinaController(IMaquinaService maquinaService, IMapper mapper, IEmpresaService empresaService)
        {
            _maquinaService = maquinaService;
            _mapper = mapper;
            _empresaService = empresaService;
        }



        /*Carga la lista de Maquinas*/
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> IndexMaquina()
        {

            List<MaquinaDTO> maquinaList = new();

            var response = await _maquinaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if(response != null && response.IsExitoso)
            {
                maquinaList = JsonConvert.DeserializeObject<List<MaquinaDTO>>(Convert.ToString(response.Resultado));
            }

            return View(maquinaList);
        }



        /*Crear maquina*/
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CrearMaquina()
        {
            //Enviar a la Vista la lista de Empresas para que se pueda elegir la empresa para la maquina

            //Llenar MaquinaViewModel
            MaquinaViewModel maquinaViewModel = new();

            var response = await _empresaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if(response != null && response.IsExitoso)
            {
                maquinaViewModel.MaquinaList = JsonConvert.DeserializeObject<List<EmpresaDTO>>(Convert.ToString(response.Resultado))
                                               .Select(e => new SelectListItem
                                               {
                                                   Text = e.Nombre,
                                                   Value = e.Id.ToString()
                                               });
            }

            return View(maquinaViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CrearMaquina(MaquinaViewModel modelo)
        {
            if(ModelState.IsValid)
            {
                var response = await _maquinaService.Crear<APIResponse>(modelo.Maquina, HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

                if(response != null && response.IsExitoso)
                {
                    TempData["exitoso"] = "Maquina creada exitosamente"; //Datos en carpeta Shared
                    return RedirectToAction(nameof(IndexMaquina));
                }
                else
                {
                    if(response.ErrorMessages.Count > 0)
                    {
                        TempData["error"] = "Ha ocurrido un ERROR al crear maquina"; //Datos en carpeta Shared
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            //En caso de que algo falle se vuelve a cargar la lista de Empresas
            var res = await _empresaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if (res != null && res.IsExitoso)
            {
                modelo.MaquinaList = JsonConvert.DeserializeObject<List<EmpresaDTO>>(Convert.ToString(res.Resultado))
                                               .Select(e => new SelectListItem
                                               {
                                                   Text = e.Nombre,
                                                   Value = e.Id.ToString()
                                               });
            }

            return View(modelo);

        }

        /*Actualizar maquina*/
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> ActualizarMaquina(int Id)
        {
            MaquinaUpdateViewModel maquinaUpdateViewModel = new();

            var response = await _maquinaService.Obtener<APIResponse>(Id, HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if(response != null && response.IsExitoso)
            {
                MaquinaDTO modelo = JsonConvert.DeserializeObject<MaquinaDTO>(Convert.ToString(response.Resultado));

                maquinaUpdateViewModel.Maquina = _mapper.Map<MaquinaUpdateDTO>(modelo);
            }

            response = await _empresaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if (response != null && response.IsExitoso)
            {
                maquinaUpdateViewModel.MaquinaList = JsonConvert.DeserializeObject<List<EmpresaDTO>>(Convert.ToString(response.Resultado))
                                               .Select(e => new SelectListItem
                                               {
                                                   Text = e.Nombre,
                                                   Value = e.Id.ToString()
                                               });
                return View(maquinaUpdateViewModel);
            }

             return NotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ActualizarMaquina(MaquinaUpdateViewModel modelo)
        {
            if (ModelState.IsValid)
            {
                var response = await _maquinaService.Actualizar<APIResponse>(modelo.Maquina, HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

                if (response != null && response.IsExitoso)
                {
                    TempData["exitoso"] = "Maquina actualizada exitosamente"; //Datos en carpeta Shared
                    return RedirectToAction(nameof(IndexMaquina));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        TempData["error"] = "Ha ocurrido un ERROR al actualizar maquina"; //Datos en carpeta Shared
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            //En caso de que algo falle se vuelve a cargar la lista de Empresas
            var res = await _empresaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if (res != null && res.IsExitoso)
            {
                modelo.MaquinaList = JsonConvert.DeserializeObject<List<EmpresaDTO>>(Convert.ToString(res.Resultado))
                                               .Select(e => new SelectListItem
                                               {
                                                   Text = e.Nombre,
                                                   Value = e.Id.ToString()
                                               });
            }

            return View(modelo);
        }

        /*Borrar maquina*/
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> RemoverMaquina(int Id)
        {
            MaquinaDeleteViewModel maquinaUpdateViewModel = new();

            var response = await _maquinaService.Obtener<APIResponse>(Id, HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if (response != null && response.IsExitoso)
            {
                MaquinaDTO modelo = JsonConvert.DeserializeObject<MaquinaDTO>(Convert.ToString(response.Resultado));

                maquinaUpdateViewModel.Maquina =modelo;
            }

            response = await _empresaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if (response != null && response.IsExitoso)
            {
                maquinaUpdateViewModel.MaquinaList = JsonConvert.DeserializeObject<List<EmpresaDTO>>(Convert.ToString(response.Resultado))
                                               .Select(e => new SelectListItem
                                               {
                                                   Text = e.Nombre,
                                                   Value = e.Id.ToString()
                                               });
                return View(maquinaUpdateViewModel);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoverMaquina(MaquinaDeleteViewModel modelo)
        {
            var response = await _maquinaService.Remover<APIResponse>(modelo.Maquina.Id, HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken));

            if(response != null && response.IsExitoso)
            {
                TempData["exitoso"] = "Maquina eliminada exitosamente"; //Datos en carpeta Shared
                return RedirectToAction(nameof(IndexMaquina));
            }
            TempData["error"] = "Ha ocurrido un ERROR al eliminar maquina"; //Datos en carpeta Shared
            return View(modelo);
        }

    }
}

tcobro_WEB -Terminado - 01-08-2023 - 8.02h/tcobro_WEB/Views/Shared/_Layout.cshtml
@using tcobro_Utilidad;
<!--Capturar la sesion de usuario-->
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAcc

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tcobro_WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tcobro_WEB.styles.css" asp-append-version="true" />

    <!--Copiar CDN de la pagina de Bootstrap para utilizar libreria(iconos,temas...)-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <!--incluye Alertas personalizadas para su uso en los Controller [POST]-->
    <partial name="_Notificacion" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tcobro_WEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <!--class: estilos || asp-area: Carpeta || asp-controller: NombreControlador || asp-action: NombreDeLaVista-->
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empresa" asp-action="IndexEmpresa">Empresa</a>
                        </li>
                        <li class="nav-item">
                            <!--class: estilos || asp-area: Carpeta || asp-controller: NombreControlador || asp-action: NombreDeLaVista-->
                            <a class="nav-link text-dark" asp-area="" asp-controller="Maquina" asp-action="IndexMaquina">Maquina</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav d-flex">
                        <!--Si la sesion no es nula y esta llena muestra el boton cerrar sesion, de lo contrario muestra iniciar sesion o registrarse-->
                        @if (httpContextAcc.HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken) != null &&
                             httpContextAcc.HttpContext.Session.GetString(DefinicionesEstaticas.SessionToken).ToString().Length > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CerrarSesion">Cerrar sesion</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Iniciar sesion</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Registrar">Registrar</a>
                            </li>
                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - tcobro_WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

tcobro_WEB -Terminado - 01-08-2023 - 8.02h/tcobro_WEB/Views/Shared/_Notificacion.cshtml
<!--Notificaciones con diseño en web se incluye en layout -> partial name="_Notificacion" para su uso-->
<!--Enlace de web Sweetalert2-->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<!--Tempdata = Se utilizan y se borran al momento de utilizarlos-->
@if (TempData["exitoso"] != null)
{
    <script>
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["exitoso"]',
            showConfirmButton: false,
            timer: 2000 
        });
    </script>
}

@if (TempData["error"] != null)
{
    <script>
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 2000
        });
    </script>
}